theme: jekyll-theme-hacker
site_name: OdicforceSounds Gifts and Challenges
site_description: Fantasy[OM] + Logic[Spirity] = Application[Expression]
repo_url: https://github.com/odicforcesounds/The-Challenge
